
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pete
 */
public class RoomSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form RoomSchedulerGUI
     */
    public RoomSchedulerGUI() {
        initComponents();
        rebuildFacultyComboBoxes();
        rebuildDateComboBoxes();
        rebuildRoomComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //need this for all combo boxes  
    public void rebuildDateComboBoxes()
    {
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray())); 
        sbdComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        cancelReservationDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }
    public static String removeFromWaitlist(String faculty, Date date, int seats){
         ArrayList<String> rooms = new ArrayList<>();
        ArrayList<String> roomsReserved = new ArrayList<>();
        roomsReserved = ReservationQueries.getJustRoomsReservedByDate(date);
        rooms = RoomQueries.getAllPossibleRooms(seats);
        
        
       String out = "";
        String room1;
        room1 = "";
        int i;
        for (i=0;i< rooms.size();i++ ) {
            room1 = rooms.get(i);
            if (rooms.size() == 0){
                break;
            }
            if (roomsReserved.contains(room1)){
                continue;
            }
            else{
                ReservationQueries.addReservationEntry(faculty, date, seats, room1);
                WaitlistQueries.cancelWaitlistEntry(faculty,date);
                out += "<html>" + faculty + " reserves " + room1 + " for " + date + " from waitlist " + "<br/>" +"<html>";
                
                break;
            }

        }
        return out;
    }
    
    public void rebuildRoomComboBoxes()
    {
        dropRoomRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getAllRooms().toArray()));        
    }
    public void rebuildFacultyComboBoxes()
    {
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray())); 
       cancelFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
       fsFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        dropRoomTabPanel = new javax.swing.JTabbedPane();
        addFacultyTab = new javax.swing.JPanel();
        addFacultyNameLabel = new javax.swing.JLabel();
        addFacultyButton = new javax.swing.JButton();
        addFacultyTextField = new javax.swing.JTextField();
        addFacultyDisplayLabel = new javax.swing.JLabel();
        reserveTab = new javax.swing.JPanel();
        reserveFacultyMemberLabel = new javax.swing.JLabel();
        reserveDateLabel = new javax.swing.JLabel();
        reserveNumberOfSeatsLabel = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        reserveNumberOfSeatsTextField = new javax.swing.JTextField();
        reserveSubmitButton = new javax.swing.JButton();
        reserveDisplayLabel = new javax.swing.JLabel();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        statusByDateTab = new javax.swing.JPanel();
        sbdDateLabel = new javax.swing.JLabel();
        sbdReservationsLabel = new javax.swing.JLabel();
        sbdSubmitButton = new javax.swing.JButton();
        sbdDisplayLabel = new javax.swing.JLabel();
        sbdComboBox = new javax.swing.JComboBox<>();
        waitlistStatusTab = new javax.swing.JPanel();
        wsDisplayWaitlistButton = new javax.swing.JButton();
        waitlistStatusDisplayLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addRoomRoomNameLabel = new javax.swing.JLabel();
        addRoomSeatsLabel = new javax.swing.JLabel();
        addRoomRoomNameTextField = new javax.swing.JTextField();
        addRoomSeatsTextField = new javax.swing.JTextField();
        addRoomDisplayLabel = new javax.swing.JLabel();
        addRoomButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addDateButton = new javax.swing.JButton();
        addDateSpinner = new javax.swing.JSpinner();
        addDateDisplayLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        facultyStatusFacultyLabel = new javax.swing.JLabel();
        facultyStatusSubmitButton = new javax.swing.JButton();
        facultyStatusDisplayLabel = new javax.swing.JLabel();
        fsFacultyComboBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        dropRoomRoomNameLabel = new javax.swing.JLabel();
        dropRoomRoomComboBox = new javax.swing.JComboBox<>();
        dropRoomDisplayLabel = new javax.swing.JLabel();
        dropRoomSubmitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cancelReservationSubmitButton = new javax.swing.JButton();
        cancelReservationFacultyNameLabel = new javax.swing.JLabel();
        cancelReservationDateComboBox = new javax.swing.JComboBox<>();
        cancelReservationDateLabel = new javax.swing.JLabel();
        cancelReservationDisplayLabel = new javax.swing.JLabel();
        cancelFacultyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.Color.gray);

        titleLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        titleLabel.setText("Room Scheduler");
        titleLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                titleLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        dropRoomTabPanel.setBackground(new java.awt.Color(255, 255, 255));
        dropRoomTabPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addFacultyTab.setBackground(new java.awt.Color(204, 204, 255));

        addFacultyNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addFacultyNameLabel.setText("Faculty Name: ");

        addFacultyButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addFacultyButton.setText("Add Faculty");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addFacultyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyTextFieldActionPerformed(evt);
            }
        });

        addFacultyDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout addFacultyTabLayout = new javax.swing.GroupLayout(addFacultyTab);
        addFacultyTab.setLayout(addFacultyTabLayout);
        addFacultyTabLayout.setHorizontalGroup(
            addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyTabLayout.createSequentialGroup()
                .addGroup(addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFacultyTabLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(addFacultyNameLabel)
                        .addGap(110, 110, 110)
                        .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFacultyTabLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(addFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFacultyTabLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(addFacultyDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        addFacultyTabLayout.setVerticalGroup(
            addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyTabLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFacultyNameLabel))
                .addGap(36, 36, 36)
                .addComponent(addFacultyDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(addFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        addFacultyNameLabel.getAccessibleContext().setAccessibleDescription("");

        dropRoomTabPanel.addTab("Add Faculty", addFacultyTab);

        reserveTab.setBackground(new java.awt.Color(204, 204, 255));

        reserveFacultyMemberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveFacultyMemberLabel.setText("Faculty Member:");

        reserveDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveDateLabel.setText("Date:");

        reserveNumberOfSeatsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveNumberOfSeatsLabel.setText("Number of Seats Required: ");

        reserveFacultyComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveFacultyComboBoxActionPerformed(evt);
            }
        });

        reserveNumberOfSeatsTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveNumberOfSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveNumberOfSeatsTextFieldActionPerformed(evt);
            }
        });

        reserveSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reserveSubmitButton.setText("Submit");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        reserveDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        reserveDateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout reserveTabLayout = new javax.swing.GroupLayout(reserveTab);
        reserveTab.setLayout(reserveTabLayout);
        reserveTabLayout.setHorizontalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reserveNumberOfSeatsLabel)
                            .addComponent(reserveDateLabel)
                            .addComponent(reserveFacultyMemberLabel))
                        .addGap(64, 64, 64)
                        .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reserveNumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(reserveSubmitButton))
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(reserveDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        reserveTabLayout.setVerticalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveFacultyMemberLabel)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reserveDateLabel)
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveNumberOfSeatsLabel)
                    .addComponent(reserveNumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(reserveDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(reserveSubmitButton)
                .addGap(49, 49, 49))
        );

        dropRoomTabPanel.addTab("Reserve", reserveTab);

        statusByDateTab.setBackground(new java.awt.Color(204, 204, 255));

        sbdDateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sbdDateLabel.setText("Date: ");

        sbdReservationsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sbdReservationsLabel.setText("Reservations on this date:");

        sbdSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sbdSubmitButton.setText("Submit");
        sbdSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbdSubmitButtonActionPerformed(evt);
            }
        });

        sbdDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sbdComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout statusByDateTabLayout = new javax.swing.GroupLayout(statusByDateTab);
        statusByDateTab.setLayout(statusByDateTabLayout);
        statusByDateTabLayout.setHorizontalGroup(
            statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusByDateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sbdDateLabel)
                    .addComponent(sbdReservationsLabel))
                .addGroup(statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusByDateTabLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(sbdDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(statusByDateTabLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(sbdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(333, Short.MAX_VALUE))))
            .addGroup(statusByDateTabLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(sbdSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusByDateTabLayout.setVerticalGroup(
            statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusByDateTabLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbdDateLabel)
                    .addComponent(sbdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(statusByDateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusByDateTabLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(sbdReservationsLabel))
                    .addGroup(statusByDateTabLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(sbdDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(sbdSubmitButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        dropRoomTabPanel.addTab("Status by Date", statusByDateTab);

        waitlistStatusTab.setBackground(new java.awt.Color(204, 204, 255));

        wsDisplayWaitlistButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wsDisplayWaitlistButton.setText("Display Waitlist");
        wsDisplayWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsDisplayWaitlistButtonActionPerformed(evt);
            }
        });

        waitlistStatusDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout waitlistStatusTabLayout = new javax.swing.GroupLayout(waitlistStatusTab);
        waitlistStatusTab.setLayout(waitlistStatusTabLayout);
        waitlistStatusTabLayout.setHorizontalGroup(
            waitlistStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waitlistStatusTabLayout.createSequentialGroup()
                .addGroup(waitlistStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(waitlistStatusTabLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(wsDisplayWaitlistButton))
                    .addGroup(waitlistStatusTabLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(waitlistStatusDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        waitlistStatusTabLayout.setVerticalGroup(
            waitlistStatusTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, waitlistStatusTabLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(waitlistStatusDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wsDisplayWaitlistButton)
                .addGap(91, 91, 91))
        );

        dropRoomTabPanel.addTab("Waitlist Status", waitlistStatusTab);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        addRoomRoomNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoomRoomNameLabel.setText("Room Name:");

        addRoomSeatsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoomSeatsLabel.setText("Seats:");

        addRoomRoomNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addRoomSeatsTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addRoomDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        addRoomButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoomButton.setText("Add Room");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRoomRoomNameLabel)
                            .addComponent(addRoomSeatsLabel))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addRoomRoomNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(addRoomSeatsTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(addRoomDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomRoomNameLabel)
                    .addComponent(addRoomRoomNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomSeatsLabel)
                    .addComponent(addRoomSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addRoomDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        dropRoomTabPanel.addTab("Add Room", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        addDateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDateButton.setText("Add Date");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        addDateSpinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDateSpinner.setModel(new javax.swing.SpinnerDateModel());

        addDateDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(addDateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(addDateButton)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(addDateDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(addDateButton)
                .addGap(38, 38, 38))
        );

        dropRoomTabPanel.addTab("Add Date", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        facultyStatusFacultyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        facultyStatusFacultyLabel.setText("Faculty Member: ");

        facultyStatusSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        facultyStatusSubmitButton.setText("Submit");
        facultyStatusSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyStatusSubmitButtonActionPerformed(evt);
            }
        });

        facultyStatusDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fsFacultyComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(facultyStatusFacultyLabel)
                        .addGap(65, 65, 65)
                        .addComponent(fsFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(facultyStatusDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(facultyStatusSubmitButton)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyStatusFacultyLabel)
                    .addComponent(fsFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(facultyStatusDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(facultyStatusSubmitButton)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        dropRoomTabPanel.addTab("Faculty Status", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        dropRoomRoomNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dropRoomRoomNameLabel.setText("Room Name: ");

        dropRoomRoomComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dropRoomDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dropRoomSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dropRoomSubmitButton.setText("Drop");
        dropRoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(dropRoomRoomNameLabel)
                        .addGap(89, 89, 89)
                        .addComponent(dropRoomRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(dropRoomDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(dropRoomSubmitButton)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropRoomRoomNameLabel)
                    .addComponent(dropRoomRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(dropRoomDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dropRoomSubmitButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        dropRoomTabPanel.addTab("Drop Room", jPanel5);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        cancelReservationSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelReservationSubmitButton.setText("Submit");
        cancelReservationSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationSubmitButtonActionPerformed(evt);
            }
        });

        cancelReservationFacultyNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelReservationFacultyNameLabel.setText("Faculty Name:");

        cancelReservationDateComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cancelReservationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelReservationDateLabel.setText("Date:");

        cancelReservationDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cancelFacultyComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelFacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFacultyComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelReservationFacultyNameLabel)
                            .addComponent(cancelReservationDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelReservationDateComboBox, 0, 141, Short.MAX_VALUE)
                            .addComponent(cancelFacultyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(cancelReservationDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(cancelReservationSubmitButton)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelReservationFacultyNameLabel)
                    .addComponent(cancelFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelReservationDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelReservationDateLabel))
                .addGap(18, 18, 18)
                .addComponent(cancelReservationDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cancelReservationSubmitButton)
                .addGap(49, 49, 49))
        );

        dropRoomTabPanel.addTab("Cancel Reservation", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dropRoomTabPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(dropRoomTabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_titleLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_titleLabelAncestorAdded

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        // TODO add your handling code here:
        String faculty;
        faculty = addFacultyTextField.getText();
        addFacultyDisplayLabel.setText(faculty + " has been added to the database.");
        Faculty.addFaculty(faculty);
        rebuildFacultyComboBoxes();
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void sbdSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbdSubmitButtonActionPerformed
        // TODO add your handling code here:
        String date1;
        date1 =sbdComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(date1);
         ArrayList<String> sbd = new ArrayList<String>();
         sbd = ReservationQueries.getReservationsByDate(date);
        int i;
        String x;
        String output = "";
        for ( i=0; i<sbd.size();i++){
            x = sbd.get(i);
            output += "<html>" +x + " <br/>" + "<html>";
        }
        sbdDisplayLabel.setText(output);
    }//GEN-LAST:event_sbdSubmitButtonActionPerformed

    private void wsDisplayWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsDisplayWaitlistButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> waitlist;
        waitlist = new ArrayList<>();
        waitlist = WaitlistQueries.getWaitlist();
        //use for loop, get size of array
        int i;
        String x;
        String output = "";
        for ( i=0; i<waitlist.size();i++){
           
            x = waitlist.get(i);
            output += "<html>" + x + " <br/>"+ "<html>" ;
            }
        if (waitlist.size() == 0) {
                output += "waitlist is empty";
        }
        waitlistStatusDisplayLabel.setText(output);
        
    }//GEN-LAST:event_wsDisplayWaitlistButtonActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        // TODO add your handling code here:
        String faculty;
        Date date;
        int seats;
        faculty =reserveFacultyComboBox.getSelectedItem().toString();
        date = Date.valueOf(reserveDateComboBox.getSelectedItem().toString());
        seats = Integer.parseInt(reserveNumberOfSeatsTextField.getText());
        ArrayList<String> rooms = new ArrayList<>();
        ArrayList<String> roomsReserved = new ArrayList<>();
        roomsReserved = ReservationQueries.getJustRoomsReservedByDate(date);
        rooms = RoomQueries.getAllPossibleRooms(seats);
        boolean waitlist;
        waitlist = false;
        String out,room;
        room = "";
        int i;
        for (i=0;i< rooms.size();i++ ) {
            room = rooms.get(i);
  
            if (roomsReserved.contains(room)){
                waitlist = true;
            }
            else{
                waitlist = false;
                break;
            }

        }
        if (rooms.size() == 0) {
                waitlist = true;
               
        }

        if (waitlist==false){
            ReservationQueries.addReservationEntry(faculty,date,seats, room);
            out = faculty + " reserves room " + room;
            reserveDisplayLabel.setText(out);
        }
        else{
            WaitlistQueries.addWaitlistEntry(faculty,date,seats);
            out = faculty + " gets waitlisted";
            reserveDisplayLabel.setText(out);

        }
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    private void reserveNumberOfSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveNumberOfSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveNumberOfSeatsTextFieldActionPerformed

    private void reserveFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveFacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveFacultyComboBoxActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(addDateSpinner.getValue());
        Date date = Date.valueOf(spinnerValue); 
        Dates.addDate(date);
        String date1 = date.toString();
        addDateDisplayLabel.setText(date1 + " has been added");
        reserveDateComboBox.addItem(date1);
        sbdComboBox.addItem(date1);
        cancelReservationDateComboBox.addItem(date1);
    }//GEN-LAST:event_addDateButtonActionPerformed

    private void facultyStatusSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyStatusSubmitButtonActionPerformed
        String faculty = fsFacultyComboBox.getSelectedItem().toString();
        ArrayList<String> reservationsByFaculty = new ArrayList<String>();
        ArrayList<String> waitlistByFaculty = new ArrayList<String>();
        reservationsByFaculty = ReservationQueries.getReservationsByFaculty(faculty);
        waitlistByFaculty = WaitlistQueries.getWaitListByFaculty(faculty);
        int i = 0;
        int j = 0;
        String out = "";
        String format = "";
        String format1 = "";
        for (i = 0;i<reservationsByFaculty.size();i++) {
            format = "<html>" + reservationsByFaculty.get(i) + " <br/>"+ "<html>";
            out += format;
        for (j=0;j<waitlistByFaculty.size();j++) {
            format1 = "<html>" + waitlistByFaculty.get(i) + " <br/>"+ "<html>";
            out += format1;
        facultyStatusDisplayLabel.setText(out);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyStatusSubmitButtonActionPerformed
//use getters to get each aspect of waitlist then use the method to add reservationFromWaitlist
    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        String room;
        
        room = addRoomRoomNameTextField.getText();
        int seats;
        seats = Integer.parseInt(addRoomSeatsTextField.getText());
        RoomQueries.addRoom(room,seats);
        ArrayList<WaitlistEntry> waitlist = new ArrayList<WaitlistEntry>();
        waitlist = WaitlistQueries.getWaitlistEntries();
        int i;
        String faculty;
        Date date;
        int seats1;
        String out = "";
        out += "<html>" + "room " + room + " gets added" + " <br/>" + "<html>";
        for (i=0;i<waitlist.size();i++) {
            faculty= waitlist.get(i).getFaculty();
            date = waitlist.get(i).getDate();
            seats1 = waitlist.get(i).getSeats();
            out += removeFromWaitlist(faculty, date, seats);
                
           
        }
        
        //just get all waitlist, see if you can add, then see if you can add again(make method remove from waitlist)
        addRoomDisplayLabel.setText(out);
        dropRoomRoomComboBox.addItem(room);
        // TODO add your handling code here:

    }//GEN-LAST:event_addRoomButtonActionPerformed

    private void cancelReservationSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationSubmitButtonActionPerformed
        String faculty;
        Date date;
        String out = "";
        faculty = cancelFacultyComboBox.getSelectedItem().toString();
        date = Date.valueOf(cancelReservationDateComboBox.getSelectedItem().toString());
        ArrayList<WaitlistEntry> waitlist = new ArrayList<WaitlistEntry>();
        waitlist = WaitlistQueries.getWaitlistEntriesByDate(date);
        ReservationQueries.cancelReservation(faculty,date);
        out += "<html>" + faculty + " " + date + " gets cancelled"+ "<br/>" + "<html>";
        int seats, i;
        String faculty1 = "";
        WaitlistQueries.deleteWaitlistEntry(faculty, date);
        for (i=0;i<waitlist.size();i++){
            WaitlistEntry wlEntry = waitlist.get(i);
            seats = wlEntry.getSeats();
            faculty = wlEntry.getFaculty();
            out+= removeFromWaitlist(faculty, date, seats);
            
                
        }
        cancelReservationDisplayLabel.setText(out);
        
         
        //remove from waitlist or reservation, 
        //if removed from reservation, check waitlist for that date, if seats<=seats then make reservation
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelReservationSubmitButtonActionPerformed

    private void dropRoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomSubmitButtonActionPerformed
        String room;
        room = dropRoomRoomComboBox.getSelectedItem().toString();
        dropRoomRoomComboBox.removeItem(room);
        RoomQueries.dropRoom(room);
        String out = "";
        ArrayList<WaitlistEntry> kickedOut = new ArrayList<WaitlistEntry>();
        kickedOut = ReservationQueries.getReservedByRoom(room);
        ReservationQueries.cancelReservationByRoom(room);
        String faculty = "";
        Date date;
        int seats;
        int i;
         for (i=0;i<kickedOut.size();i++){
             WaitlistEntry wlEntry = kickedOut.get(i);
             seats = wlEntry.getSeats();
             date = wlEntry.getDate();
             faculty = wlEntry.getFaculty();
             WaitlistQueries.addWaitlistEntry(faculty,date, seats);
             out += "<html>" + faculty + " " + date + " is moved to waitlist"+ "<br/>" +"<html>";
         }
         for (i=0;i<kickedOut.size();i++){
             WaitlistEntry wlEntry = kickedOut.get(i);
             seats = wlEntry.getSeats();
             date = wlEntry.getDate();
             faculty = wlEntry.getFaculty();
             out+= removeFromWaitlist(faculty, date, seats);
             
         }
        // if they had that room, first get date and seats, remove them from reservation, move to waitlist (tell them)
        //check to see if they can make a new reservation and tell them if they can 
        //timestamp for just reservation waitlist entry?
        dropRoomDisplayLabel.setText(out);
    }//GEN-LAST:event_dropRoomSubmitButtonActionPerformed

    private void addFacultyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFacultyTextFieldActionPerformed

    private void cancelFacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelFacultyComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RoomSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDateButton;
    private javax.swing.JLabel addDateDisplayLabel;
    private javax.swing.JSpinner addDateSpinner;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JLabel addFacultyDisplayLabel;
    private javax.swing.JLabel addFacultyNameLabel;
    private javax.swing.JPanel addFacultyTab;
    private javax.swing.JTextField addFacultyTextField;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JLabel addRoomDisplayLabel;
    private javax.swing.JLabel addRoomRoomNameLabel;
    private javax.swing.JTextField addRoomRoomNameTextField;
    private javax.swing.JLabel addRoomSeatsLabel;
    private javax.swing.JTextField addRoomSeatsTextField;
    private javax.swing.JComboBox<String> cancelFacultyComboBox;
    private javax.swing.JComboBox<String> cancelReservationDateComboBox;
    private javax.swing.JLabel cancelReservationDateLabel;
    private javax.swing.JLabel cancelReservationDisplayLabel;
    private javax.swing.JLabel cancelReservationFacultyNameLabel;
    private javax.swing.JButton cancelReservationSubmitButton;
    private javax.swing.JLabel dropRoomDisplayLabel;
    private javax.swing.JComboBox<String> dropRoomRoomComboBox;
    private javax.swing.JLabel dropRoomRoomNameLabel;
    private javax.swing.JButton dropRoomSubmitButton;
    private javax.swing.JTabbedPane dropRoomTabPanel;
    private javax.swing.JLabel facultyStatusDisplayLabel;
    private javax.swing.JLabel facultyStatusFacultyLabel;
    private javax.swing.JButton facultyStatusSubmitButton;
    private javax.swing.JComboBox<String> fsFacultyComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JLabel reserveDateLabel;
    private javax.swing.JLabel reserveDisplayLabel;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JLabel reserveFacultyMemberLabel;
    private javax.swing.JLabel reserveNumberOfSeatsLabel;
    private javax.swing.JTextField reserveNumberOfSeatsTextField;
    private javax.swing.JButton reserveSubmitButton;
    private javax.swing.JPanel reserveTab;
    private javax.swing.JComboBox<String> sbdComboBox;
    private javax.swing.JLabel sbdDateLabel;
    private javax.swing.JLabel sbdDisplayLabel;
    private javax.swing.JLabel sbdReservationsLabel;
    private javax.swing.JButton sbdSubmitButton;
    private javax.swing.JPanel statusByDateTab;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel waitlistStatusDisplayLabel;
    private javax.swing.JPanel waitlistStatusTab;
    private javax.swing.JButton wsDisplayWaitlistButton;
    // End of variables declaration//GEN-END:variables
}


